version: "3.4"
services:
  mongo:
    image: mongo
    networks:
      - net
    hostname: mongo
    restart: always
    environment:
      AUTH: "no"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  server:
    hostname: server
    networks:
      - net
    image: batoch/chatserver
    container_name: node_server_container
    depends_on:
      - mongo
    environment:
      MYSQL_HOST_IP: mongo
    volumes:
      - .:/app
    links:
      - mongo
    command: npm start
  reverse-proxy:
    image: nginx
    restart: 'unless-stopped'
    networks:
      - net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
#      - 443:443
    depends_on:
      - server
volumes:
  mongodb:
networks:
  net:
    driver: bridge