version: "3.4"
services:
  mongo:
    image: mangoraft/mongodb-arm
    container_name: mongo_container
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
      AUTH: "no"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: node_server_container
    depends_on:
      - mongo
    environment:
      MYSQL_HOST_IP: mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo
    command: npm start
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server
volumes:
  mongodb:
