version: "3.4"
services:
  mongo:
    image: mongo
    networks:
      - net
    container_name: mongo_container
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
      AUTH: "no"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  server:
    hostname: server
    networks:
      - net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: node_server_container
    depends_on:
      - mongo
    environment:
      MYSQL_HOST_IP: mongo
    volumes:
      - .:/app
    links:
      - mongo
    command: npm start
  reverse-proxy:
    image: nginx
    networks:
      - net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
#      - 443:443
    depends_on:
      - server
volumes:
  mongodb:
networks:
  net:
    driver: bridge