version: "3.4"
services:
  mongo:
    image: mongo
    hostname: ${MONGOHOSTNAME:-mongo}
    restart: always
    container_name: mongo_db_container
    environment:
      AUTH: "no"
    volumes:
      - mongodb:/data/db
    networks:
      - net
  server:
    image: batoch/chatserver
    hostname: server
    restart: always
    container_name: node_server_container
    depends_on:
      - mongo
    command: npm start
    networks:
      - net
  reverse-proxy:
    image: nginx
    restart: always
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - server
    networks:
      - net
    ports:
      - 80:80
#      - 443:443
volumes:
  mongodb:
networks:
  net:
    driver: bridge
