services:
  server:
    labels:
      - 'traefik.enable=true'
  reverse-proxy:
    image: traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.toml:/traefik.toml'
    ports:
      - 8080:8080