services:
  server:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.chat.loadbalancer.server.port=3000'
      - 'traefik.http.routers.chat.rule=PathPrefix(`/`)'
  
  reverse-proxy:
    image: traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.toml:/traefik.toml'
    ports:
      - 8080:8080