version: "3.4"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - .:/app
  mongo:
    image: mangoraft/mongodb-arm