# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Socketchargithub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_24203e9c594b45d9acf32e57a4fd58fd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c208cda1b30a4f5ba69e61be8155a668 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_24203e9c594b45d9acf32e57a4fd58fd }}/socketchat:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Socketchargithub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1598fe2e7b4b414d82e951c843149038 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_24203e9c594b45d9acf32e57a4fd58fd }}/socketchat:${{ github.sha }}'