name: '[builder] CI for releases'

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'     
                required: true
                default: 'warning'


jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2.4.0
        -
            name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        # https://github.com/docker/setup-qemu-action
        - 
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1.2.0
        # https://github.com/docker/setup-buildx-action
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2.4.0
            with:
                version: latest
        -
            name: Build dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/amd64,linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag ${{ secrets.DOCKERHUB_USERNAME }}/chatserver:latest
